language: node_js

node_js:
  - "node"
  - "10"

notifications:
  email: false

branches:
  only:
    - master
    - /^greenkeeper.*$/
  
before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
  - npm install -g greenkeeper-lockfile
install:
  - npm install
before_script:
  - greenkeeper-lockfile-update
script:
  - commitlint-travis
  - npm run test:prod && npm run build
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - npm run report-coverage
