language: node_js

node_js:
  - 'node'

notifications:
  email: false

branches:
  only:
    - master
    - /^greenkeeper.*$/

before_install:
  - npm install -g yarn
  - npm install -g greenkeeper-lockfile

install:
  - yarn install

before_script:
  - greenkeeper-lockfile-update

script:
  - yarn test

after_success:
  - yarn report-coverage

after_script:
  - greenkeeper-lockfile-upload
