language: node_js

node_js:
  - "node"

notifications:
  email: false

branches:
  only:
    - master
    - /^greenkeeper.*$/
  
before_install:
  - npm install -g npm@latest
  - npm install -g greenkeeper-lockfile

install:
  - npm install

before_script:
  - greenkeeper-lockfile-update

script:
  - commitlint-travis
  - npm run test:prod && npm run build

after_success:
  - npm run report-coverage
  
after_script:
  - greenkeeper-lockfile-upload
