language: node_js
node_js:
  - "node"
  - "8"
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper.*$/

script:
  - commitlint-travis
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
